INSTRUMENTS = {
    '11-string-alto-guitar': {'nom': '11-string Alto Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '12-string-guitar': {'nom': '12-string Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '5-string-electric-bass': {'nom': '5-str. Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '5-string-electric-bass-high-c': {'nom': '5-str. Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '5-string-electric-bass-tab': {'nom': '5-str. Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '5-string-electric-bass-tab-high-c': {'nom': '5-str. Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '6-string-electric-bass': {'nom': '6-str. Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '6-string-electric-bass-tab': {'nom': '6-str. Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '7-string-guitar': {'nom': '7-string Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    '7-string-guitar-tablature': {'nom': '7-string Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'a-bass-clarinet': {'nom': 'Bass Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-bass-clarinet-bass-clef)': {'nom': 'Bass Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-bass-duduk': {'nom': 'A Bass Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-clarinet': {'nom': 'Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-cornet': {'nom': 'Cornet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-dizi': {'nom': 'A Dizi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-duduk': {'nom': 'A Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'a-piccolo-trumpet': {'nom': 'Piccolo Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'a-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ab-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'accordion': {'nom': 'Accordion', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'acoustic-bass': {'nom': 'Acoustic Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'almglocken': {'nom': 'Almglocken', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alphorn': {'nom': 'Alphorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'alto': {'nom': 'Alto', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-bugle': {'nom': 'Alto Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-c-clef': {'nom': 'Alto', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-chalumeau': {'nom': 'Alto Chalumeau', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-clarinet': {'nom': 'Alto Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-cornamuse': {'nom': 'Alto Cornamuse', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-cornett': {'nom': 'Alto Cornett', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-crumhorn': {'nom': 'Alto Crumhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-flute': {'nom': 'Alto Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-gemshorn': {'nom': 'Alto Gemshorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-guitar': {'nom': 'Alto Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'alto-kalimba': {'nom': 'Alto Kalimba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-kelhorn': {'nom': 'Alto Kelhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-mandola': {'nom': 'Alto Mandola', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-recorder': {'nom': 'Alto Recorder', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-sackbut': {'nom': 'Alto Sackbut', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-sarrusophone': {'nom': 'Alto Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-saxophone': {'nom': 'Alto Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-shawm': {'nom': 'Alto Shawm', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-sheng': {'nom': 'Alto Sheng', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-steel-drums': {'nom': 'Alto Steel Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-trombone': {'nom': 'Alto Trombone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'alto-viol': {'nom': 'Alto Viol', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'anvil': {'nom': 'Anvil', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'archlute-14-course': {'nom': 'Archlute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'atmosphere-synth': {'nom': 'Atmosphere Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'aulochrome': {'nom': 'Aulochrome', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'automobile-brake-drums': {'nom': 'Automobile Brake Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'b-duduk': {'nom': 'B Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bagpipe': {'nom': 'Bagpipe', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'balalaika': {'nom': 'balalaika', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'balalaika-alto': {'nom': 'Alto Balalaika', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'balalaika-bass': {'nom': 'Bass Balalaika', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'balalaika-contrabass': {'nom': 'Contrabass Balalaika', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'balalaika-piccolo': {'nom': 'Piccolo Balalaika', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'balalaika-prima': {'nom': 'Prima Balalaika', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'balalaika-secunda': {'nom': 'Secunda Balalaika', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bamboo-wind-chimes': {'nom': 'Bamboo Wind Chimes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bandoneon': {'nom': 'Bandoneon', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bandurria': {'nom': 'Bandurria', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bandurria-tablature': {'nom': 'Bandurria', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'banjo': {'nom': 'Banjo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'banjo-tablature': {'nom': 'Banjo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone': {'nom': 'Baritone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'baritone-bugle': {'nom': 'Baritone Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone-c-clef': {'nom': 'Baritone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone-guitar': {'nom': 'Baritone Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'baritone-horn': {'nom': 'Baritone Horn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'baritone-horn-central-europe': {'nom': 'Baritone Horn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'baritone-horn-central-europe-treble': {'nom': 'Baritone Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone-horn-treble': {'nom': 'Baritone Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone-sarrusophone': {'nom': 'Baritone Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone-saxophone': {'nom': 'Baritone Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baritone-ukulele': {'nom': 'Baritone Ukulele', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baroque-lute-13-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baroque-oboe': {'nom': 'Baroque Oboe', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baroque-trumpet': {'nom': 'baroque-trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'baryton': {'nom': 'Baryton', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass': {'nom': 'Bass', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-chalumeau': {'nom': 'Bass Chalumeau', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-clarinet': {'nom': 'bass-clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-cornamuse': {'nom': 'Bass Cornamuse', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-crumhorn': {'nom': 'Bass Crumhorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-drum': {'nom': 'Bass Drum', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-eb-tuba': {'nom': 'E♭ Bass Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-f-tuba': {'nom': 'F Bass Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-flute': {'nom': 'Bass Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-gemshorn': {'nom': 'Bass Gemshorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-guitar': {'nom': 'Bass Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'bass-guitar-tablature': {'nom': 'Bass Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'bass-harmonica': {'nom': 'Bass Harmonica', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-harmonica-hohner': {'nom': 'Bass Hohner Harmonica', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-harmonica-huang': {'nom': 'Bass Huang Harmonica', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-kelhorn': {'nom': 'Bass Kelhorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-marimba': {'nom': 'Bass Marimba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-oboe': {'nom': 'Bass Oboe', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-recorder': {'nom': 'Bass Recorder', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-sackbut': {'nom': 'Bass Sackbut', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-sarrusophone': {'nom': 'Bass Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-saxophone': {'nom': 'Bass Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-shawm': {'nom': 'Bass Shawm', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-sheng': {'nom': 'Bass Sheng', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-steel-drums': {'nom': 'Bass Steel Drums', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-synthesizer': {'nom': 'Bass Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bass-trombone': {'nom': 'Bass Trombone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bass-trumpet': {'nom': 'bass-trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'basset-clarinet': {'nom': 'Basset Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'basset-horn': {'nom': 'Basset Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bassoon': {'nom': 'Bassoon', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bb-alto-ocarina': {'nom': 'B♭ Alto Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-baroque-trumpet': {'nom': 'Baroque Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-bass-clarinet': {'nom': 'Bass Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-bass-clarinet-bass-clef': {'nom': 'Bass Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-bass-ophicleide': {'nom': 'Bass Ophicleide', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bb-bass-trumpet': {'nom': 'Bass Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-clarinet': {'nom': 'Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-cornet': {'nom': 'Cornet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-duduk': {'nom': 'B♭ Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-horn-alto': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-horn-basso': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-piccolo-trumpet': {'nom': 'Piccolo Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'bb-soprano-ocarina': {'nom': 'B♭ Soprano Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-sousaphone': {'nom': 'Sousaphone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bb-sousaphone-treble': {'nom': 'Sousaphone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-tuba': {'nom': 'B♭ Contrabass Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bb-tuba-treble': {'nom': 'Contrabass Tuba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bb-wagner-tuba': {'nom': 'Wagner Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bb-xaphoon': {'nom': 'Pocket Sax', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bell-plate': {'nom': 'Bell Plate', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bell-tree': {'nom': 'Bell Tree', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'berda': {'nom': 'Berda', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'bflat-tin-whistle': {'nom': 'B♭ Tin Whistle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bongos': {'nom': 'Bongos', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bouzouki-3-course': {'nom': 'Bouzouki', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bouzouki-4-course': {'nom': 'Bouzouki', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bowed-synth': {'nom': 'Bowed Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bowl-gongs': {'nom': 'Bowl Gongs', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'boy-soprano': {'nom': 'Boy Soprano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'brac': {'nom': 'Brač', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'brass': {'nom': 'Brass', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'brass-synthesizer': {'nom': 'Brass Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'brightness-synth': {'nom': 'Brightness Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bugarija': {'nom': 'Bugarija', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'bugle': {'nom': 'Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-alto-ocarina': {'nom': 'C Alto Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-baroque-trumpet': {'nom': 'Baroque Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-bass-ocarina': {'nom': 'C Bass Ocarina', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'c-bass-ophicleide': {'nom': 'Bass Ophicleide', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'c-bass-trumpet': {'nom': 'Bass Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-clarinet': {'nom': 'Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-cornet': {'nom': 'Cornet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-dizi': {'nom': 'C Dizi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-duduk': {'nom': 'C Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-horn-alto': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-horn-bass': {'nom': 'Horn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'c-quena': {'nom': 'C Quena', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-soprano-ocarina': {'nom': 'C Soprano Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-tin-whistle': {'nom': 'C Tin Whistle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'c-tuba': {'nom': 'C Contrabass Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'cabasa': {'nom': 'Cabasa', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'carillon': {'nom': 'Carillon', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'castanets': {'nom': 'Castanets', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cavaquinho': {'nom': 'Cavaquinho', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'cavaquinho-tablature': {'nom': 'Cavaquinho', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'celesta': {'nom': 'Celesta', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cello-steel-drums': {'nom': 'Cello Steel Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'celo': {'nom': 'Čelo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'chains': {'nom': 'Chains', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'chalumeau': {'nom': 'chalumeau', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'chinese-cymbal': {'nom': 'China Cymbal', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'chinese-tom-toms': {'nom': 'Chinese Tom-Toms', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'choir-synth': {'nom': 'Choir Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cimbalom': {'nom': 'Cimbalom', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cimbasso': {'nom': 'Cimbasso', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'clarinet': {'nom': 'clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'claves': {'nom': 'Claves', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'clavichord': {'nom': 'Clavichord', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'clavinet': {'nom': 'Clavinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'concertina': {'nom': 'Concertina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'conch': {'nom': 'Conch', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'congas': {'nom': 'Congas', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'contra-alto-clarinet': {'nom': 'Contra-alto Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'contra-alto-flute': {'nom': 'Contra-alto Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'contra-guitar': {'nom': 'Contra Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass': {'nom': 'Contrabass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass-bugle': {'nom': 'Contrabass Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass-clarinet': {'nom': 'Contrabass Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass-flute': {'nom': 'Contrabass Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass-marimba': {'nom': 'Contrabass Marimba', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'contrabass-recorder': {'nom': 'Contrabass Recorder', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'contrabass-sarrusophone': {'nom': 'Contrabass Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass-saxophone': {'nom': 'Contrabass Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabass-trombone': {'nom': 'Contrabass Trombone', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'contrabasses': {'nom': 'Contrabasses', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contrabassoon': {'nom': 'Contrabassoon', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'contralto': {'nom': 'Contralto', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cornamuse': {'nom': 'cornamuse', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cornett': {'nom': 'cornett', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cornettino': {'nom': 'Cornettino', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'countertenor': {'nom': 'Countertenor', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cowbell': {'nom': 'Cowbell', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'crash-cymbal': {'nom': 'Suspended Cymbal', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cromorne': {'nom': 'Cromorne', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'crotales': {'nom': 'Crotales', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'crumhorn': {'nom': 'crumhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'crystal-synth': {'nom': 'Crystal Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cuica': {'nom': 'Cuica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'cymbal': {'nom': 'Cymbals', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-baroque-trumpet': {'nom': 'Baroque Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-clarinet': {'nom': 'Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-dizi': {'nom': 'D Dizi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-duduk': {'nom': 'D Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-quena': {'nom': 'D Quena', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-tin-whistle': {'nom': 'D Tin Whistle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'd-violone': {'nom': 'D Violone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'd-xaphoon': {'nom': 'Pocket Sax', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'danso': {'nom': 'Danso', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'db-piccolo': {'nom': 'Piccolo', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'didgeridoo': {'nom': 'Didgeridoo', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'double-bass': {'nom': 'double-bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'double-contrabass-flute': {'nom': 'Double Contrabass Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'drum-kit-4': {'nom': 'Drum Kit', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'drum-kit-5': {'nom': 'Drum Kit', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'drumset': {'nom': 'Drum Kit', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'duduk': {'nom': 'duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'dulcian': {'nom': 'Dulcian', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'dulcimer': {'nom': 'Dulcimer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'e-dizi': {'nom': 'E Dizi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'e-duduk': {'nom': 'E Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'e-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'e-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-alto-horn': {'nom': 'Alto Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-alto-ophicleide': {'nom': 'Alto Ophicleide', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-baroque-trumpet': {'nom': 'Baroque Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-bass-trumpet': {'nom': 'Bass Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-clarinet': {'nom': 'Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-contrabass-ophicleide': {'nom': 'Contrabass Ophicleide', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'eb-cornet': {'nom': 'Cornet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-piccolo': {'nom': 'Piccolo', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'eb-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'eb-tuba': {'nom': 'eb-tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'eb-tuba-treble': {'nom': 'Bass Tuba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'echoes-synth': {'nom': 'Echoes Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'effect-synth': {'nom': 'Effect Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'electric-bass': {'nom': 'Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'electric-bass-4-str-tab': {'nom': 'Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'electric-guitar': {'nom': 'Electric Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'electric-guitar-tablature': {'nom': 'Electric Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'electric-guitar-treble-clef': {'nom': 'Electric Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'electric-piano': {'nom': 'Electric Piano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'english-flageolet': {'nom': 'English Flageolet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'english-horn': {'nom': 'English Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'erhu': {'nom': 'Erhu', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'euphonium': {'nom': 'Euphonium', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'euphonium-bugle': {'nom': 'Euphonium Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'euphonium-treble': {'nom': 'Euphonium', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-alto-horn': {'nom': 'Alto Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-alto-ocarina': {'nom': 'F Alto Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-alto-ophicleide': {'nom': 'Alto Ophicleide', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-baroque-trumpet': {'nom': 'Baroque Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-dizi': {'nom': 'F Dizi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-duduk': {'nom': 'F Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-quena': {'nom': 'F Quena', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-soprano-ocarina': {'nom': 'F Soprano Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-trumpet': {'nom': 'Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'f-tuba': {'nom': 'f-tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'f-wagner-tuba': {'nom': 'Wagner Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'fife': {'nom': 'B♭ Fife', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'finger-cymbals': {'nom': 'Finger Cymbals', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'finger-snap': {'nom': 'Finger Snap', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'fiscorn': {'nom': 'Fiscorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'flageolet': {'nom': 'flageolet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'flexatone': {'nom': 'Flexatone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'flugelhorn': {'nom': 'Flugelhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'flute': {'nom': 'Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'frame-drum': {'nom': 'Frame Drum', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'french-flageolet': {'nom': 'French Flageolet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'fretless-electric-bass': {'nom': 'Fretless Electric Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'g-alto-ocarina': {'nom': 'G Alto Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-clarinet': {'nom': 'Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-dizi': {'nom': 'G Dizi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-duduk': {'nom': 'G Duduk', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-quena': {'nom': 'G Quena', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-soprano-ocarina': {'nom': 'G Soprano Ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'g-xaphoon': {'nom': 'Pocket Sax', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'garklein-recorder': {'nom': 'Garklein Recorder', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'gemshorn': {'nom': 'gemshorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'glass-harmonica': {'nom': 'Glass Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'glass-wind-chimes': {'nom': 'Glass Wind Chimes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'glockenspiel': {'nom': 'Glockenspiel', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'goblins-synth': {'nom': 'Goblins Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'grand-piano': {'nom': 'Grand Piano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'great-bass-shawm': {'nom': 'Great Bass Shawm', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'greatbass-crumhorn': {'nom': 'Greatbass Crumhorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'greatbass-kelhorn': {'nom': 'Greatbass Kelhorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'greatbass-recorder': {'nom': 'Greatbass Recorder', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'guiro': {'nom': 'Güiro', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'guitar-nylon': {'nom': 'Classical Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'guitar-nylon-tablature': {'nom': 'Classical Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'guitar-nylon-treble-clef': {'nom': 'Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'guitar-steel': {'nom': 'Acoustic Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'guitar-steel-drums': {'nom': 'Guitar Steel Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'guitar-steel-tablature': {'nom': 'Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'guitar-steel-treble-clef': {'nom': 'Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'halo-synth': {'nom': 'Halo Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'hammond-organ': {'nom': 'Hammond Organ', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'hand-bells': {'nom': 'Hand Bells', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'hand-clap': {'nom': 'Hand Clap', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica': {'nom': 'harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-c12c': {'nom': '12-Hole C Chromatic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-c12g': {'nom': '12-Hole G Chromatic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-c12tenor-c': {'nom': '12-Hole Tenor C Chromatic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-c14c': {'nom': '14-Hole C Chromatic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-c16c': {'nom': '16-Hole C Chromatic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-chordet': {'nom': '20-Hole Chordet Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10a': {'nom': '10-Hole A Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10c': {'nom': '10-Hole C Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10d': {'nom': '10-Hole D Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10f': {'nom': '10-Hole F Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10g': {'nom': '10-Hole G Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10high-g': {'nom': '10-Hole High G Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonica-d10low-d': {'nom': '10-Hole Low D Diatonic Harmonica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harmonium': {'nom': 'Harmonium', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harp': {'nom': 'Harp', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'harpsichord': {'nom': 'Harpsichord', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'heckelphone': {'nom': 'Heckelphone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'heckelphone-clarinet': {'nom': 'Heckelphone-clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'helicon': {'nom': 'Helicon', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'hi-hat': {'nom': 'Hi-hat', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'honky-tonk-piano': {'nom': 'Honky Tonk Piano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'horagai': {'nom': 'Horagai', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'horn': {'nom': 'Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'hyperbass-flute': {'nom': 'Hyperbass Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'irish-flute': {'nom': 'Irish Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'irish-tenor-banjo': {'nom': 'Irish Tenor Banjo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'irish-tenor-banjo-tablature': {'nom': 'Irish Tenor Banjo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'iron-pipes': {'nom': 'Iron Pipes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'kalimba': {'nom': 'Kalimba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'kazoo': {'nom': 'Kazoo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'koto': {'nom': 'Koto', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'kuhlohorn': {'nom': 'Kuhlohorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'laud': {'nom': 'Laúd', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'laud-tablature': {'nom': 'Laúd', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'lupophone': {'nom': 'Lupophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'lute': {'nom': 'Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'lute-tablature': {'nom': 'Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mallet-synthesizer': {'nom': 'Mallet Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mandocello': {'nom': 'Mandocello', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'mandola': {'nom': 'Mandola', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mandolin': {'nom': 'Mandolin', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mandolin-tablature': {'nom': 'Mandolin', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'maracas': {'nom': 'Maracas', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'marching-bass-drums': {'nom': 'Bass Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'marching-cymbals': {'nom': 'Cymbals', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'marching-snare': {'nom': 'Snare Drum', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'marching-tenor-drums': {'nom': 'Tenor Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'marimba': {'nom': 'Marimba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'marimba-single': {'nom': 'Marimba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mark-tree': {'nom': 'Mark Tree', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mellophon-bugle': {'nom': 'Mellophone Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mellophone': {'nom': 'Mellophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'melodica': {'nom': 'Melodica', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'melody-saxophone': {'nom': 'Melody Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'men': {'nom': 'Men', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'metal-castanets': {'nom': 'Metal Castanets', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'metal-wind-chimes': {'nom': 'Metal Wind Chimes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'metallic-synth': {'nom': 'Metallic Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'metallophone': {'nom': 'metallophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mezzo-soprano': {'nom': 'Mezzo-soprano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mezzo-soprano-c-clef': {'nom': 'Mezzo-soprano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mezzo-soprano-saxophone': {'nom': 'Mezzo-Soprano Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'military-drum': {'nom': 'Field Drum', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mtn-dulcimer-baritone': {'nom': 'Mtn. Dulcimer - Baritone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mtn-dulcimer-bartn-chrom-tab': {'nom': 'Mtn. Dulcimer - Baritone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mtn-dulcimer-bass': {'nom': 'Mtn. Dulcimer - Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mtn-dulcimer-bass-chrom-tab': {'nom': 'Mtn. Dulcimer - Bass', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mtn-dulcimer-std': {'nom': 'Mtn. Dulcimer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'mtn-dulcimer-std-chrom-tab': {'nom': 'Mtn. Dulcimer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'musical-glasses': {'nom': 'Musical Glasses', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'musical-saw': {'nom': 'Musical Saw', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'new-age-synth': {'nom': 'New Age Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'nyckelharpa': {'nom': 'Nyckelharpa', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'oboe': {'nom': 'Oboe', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'oboe-d'amore': {'nom': 'Oboe d’amore', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'oboe-da-caccia': {'nom': 'Oboe da caccia', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ocarina': {'nom': 'ocarina', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'octave-mandolin': {'nom': 'Octave Mandolin', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'octavin': {'nom': 'Octavin', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'octobass': {'nom': 'Octobass', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ondes-martenot': {'nom': 'Ondes Martenot', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ophicleide': {'nom': 'ophicleide', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'orff-alto-glockenspiel': {'nom': 'Orff Alto Glockenspiel', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-alto-metallophone': {'nom': 'Orff Alto Metallophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-alto-xylophone': {'nom': 'Orff Alto Xylophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-bass-metallophone': {'nom': 'Orff Bass Metallophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-bass-xylophone': {'nom': 'Orff Bass Xylophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-soprano-glockenspiel': {'nom': 'Orff Soprano Glockenspiel', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-soprano-metallophone': {'nom': 'Orff Soprano Metallophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'orff-soprano-xylophone': {'nom': 'Orff Soprano Xylophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'organ': {'nom': 'Organ', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'oud': {'nom': 'Oud', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'pad-synth': {'nom': 'Pad Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'pan-flute': {'nom': 'Pan Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'pardessus-de-viole': {'nom': 'Pardessus de viole', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'pedal-steel-guitar': {'nom': 'Pedal Steel Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'percussion': {'nom': 'Percussion', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'percussion-synthesizer': {'nom': 'Percussion Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'percussive-organ': {'nom': 'Percussive Organ', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'piano': {'nom': 'Piano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'piccolo': {'nom': 'Piccolo', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'piccolo-clarinet': {'nom': 'Piccolo Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'piccolo-heckelphone': {'nom': 'Piccolo Heckelphone', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'piccolo-oboe': {'nom': 'Piccolo Oboe', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'piccolo-snare-drum': {'nom': 'Piccolo Snare', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'piccolo-trumpet': {'nom': 'piccolo-trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 1},
    'pipe-organ': {'nom': 'Pipe Organ', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'pocket-trumpet': {'nom': 'Pocket Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'poly-synth': {'nom': 'Poly Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'posthorn': {'nom': 'Posthorn', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'prim': {'nom': 'Prim', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'quena': {'nom': 'quena', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'quijada': {'nom': 'Quijada', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'rackett': {'nom': 'Rackett', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'rag-dung': {'nom': 'Rag Dung', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'rain-synth': {'nom': 'Rain Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ratchet': {'nom': 'Ratchet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'rauschpfeife': {'nom': 'rauschpfeife', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'recorder': {'nom': 'recorder', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'reed-contrabass': {'nom': 'Reed Contrabass', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'reed-organ': {'nom': 'Reed Organ', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ren.-tenor-lute-10-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ren.-tenor-lute-5-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ren.-tenor-lute-6-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ren.-tenor-lute-7-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ren.-tenor-lute-8-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ren.-tenor-lute-9-course': {'nom': 'Tenor Lute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ride-cymbal': {'nom': 'Ride Cymbal', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'rotary-organ': {'nom': 'Rotary Organ', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'roto-toms': {'nom': 'Roto-Toms', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sandpaper-blocks': {'nom': 'Sandpaper Blocks', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sarrusophone': {'nom': 'sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'saw-synth': {'nom': 'Saw Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'saxhorn': {'nom': 'Saxhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'saxophone': {'nom': 'saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sci-fi-synth': {'nom': 'Sci-fi Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'serpent': {'nom': 'Serpent', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'shaker': {'nom': 'Shaker', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'shakuhachi': {'nom': 'Shakuhachi', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'shamisen': {'nom': 'Shamisen', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'shell-wind-chimes': {'nom': 'Shell Wind Chimes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'shenai': {'nom': 'Shenai', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sheng': {'nom': 'sheng', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'shofar': {'nom': 'Shofar', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sine-synth': {'nom': 'Sine Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sitar': {'nom': 'Sitar', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'slap': {'nom': 'Slap', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sleigh-bells': {'nom': 'Sleigh Bells', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'slide-trumpet': {'nom': 'Slide Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'slide-whistle': {'nom': 'Slide Whistle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'slit-drum': {'nom': 'Slit Drum', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'snare-drum': {'nom': 'Snare Drum', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranino-chalumeau': {'nom': 'Sopranino Chalumeau', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranino-rauschpfeife': {'nom': 'Sopranino Rauschpfeife', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranino-recorder': {'nom': 'Sopranino Recorder', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranino-sarrusophone': {'nom': 'Sopranino Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranino-saxophone': {'nom': 'Sopranino Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranino-shawm': {'nom': 'Sopranino Shawm', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sopranissimo-saxophone': {'nom': 'Sopranissimo Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano': {'nom': 'Soprano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-bugle': {'nom': 'Soprano Bugle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-c-clef': {'nom': 'Soprano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-chalumeau': {'nom': 'Soprano Chalumeau', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-clarinet': {'nom': 'Soprano Clarinet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-cornamuse': {'nom': 'Soprano Cornamuse', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-cornett': {'nom': 'Soprano Cornett', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-crumhorn': {'nom': 'Soprano Crumhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-flute': {'nom': 'Soprano Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-gemshorn': {'nom': 'Soprano Gemshorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-guitar': {'nom': 'Soprano Guitar', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'soprano-kelhorn': {'nom': 'Soprano Kelhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-rauschpfeife': {'nom': 'Soprano Rauschpfeife', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-recorder': {'nom': 'Soprano Recorder', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-sarrusophone': {'nom': 'Soprano Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-saxophone': {'nom': 'Soprano Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-shawm': {'nom': 'Soprano Shawm', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-sheng': {'nom': 'Soprano Sheng', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-steel-drums': {'nom': 'Soprano Steel Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soprano-trombone': {'nom': 'Soprano Trombone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'soundtrack-synth': {'nom': 'Soundtrack Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'sousaphone': {'nom': 'Sousaphone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'splash-cymbal': {'nom': 'Splash Cymbal', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'square-synth': {'nom': 'Square Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'stamp': {'nom': 'Stamp', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'steel-drums': {'nom': 'Steel Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'stones': {'nom': 'Stones', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'string-synthesizer': {'nom': 'String Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'strings': {'nom': 'Strings', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'subcontra-alto-flute': {'nom': 'Sub Contra-alto Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'subcontrabass-saxophone': {'nom': 'Subcontrabass Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': -1},
    'subcontrabass-tuba': {'nom': 'Sub-Contrabass Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': -1},
    'sweep-synth': {'nom': 'Sweep Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tablas': {'nom': 'Tablas', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tam-tam': {'nom': 'Tam-tam', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tambourine': {'nom': 'Tambourine', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tarogato': {'nom': 'Tarogato', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'temple-blocks': {'nom': 'Temple Blocks', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor': {'nom': 'Tenor', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-banjo': {'nom': 'Tenor Banjo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-c-clef': {'nom': 'Tenor', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-chalumeau': {'nom': 'Tenor Chalumeau', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-cornamuse': {'nom': 'Tenor Cornamuse', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-cornett': {'nom': 'Tenor Cornett', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-crumhorn': {'nom': 'Tenor Crumhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-gemshorn': {'nom': 'Tenor Gemshorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-kelhorn': {'nom': 'Tenor Kelhorn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-mandola': {'nom': 'Tenor Mandola', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-recorder': {'nom': 'Tenor Recorder', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-sackbut': {'nom': 'Tenor Sackbut', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-sarrusophone': {'nom': 'Tenor Sarrusophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-saxophone': {'nom': 'Tenor Saxophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-shawm': {'nom': 'Tenor Shawm', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-sheng': {'nom': 'Tenor Sheng', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-steel-drums': {'nom': 'Tenor Steel Drums', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-trombone': {'nom': 'Tenor Trombone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'tenor-trumpet': {'nom': 'Tenor Trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-ukulele': {'nom': 'Tenor Ukulele', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tenor-viol': {'nom': 'Tenor Viol', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'theorbo-14-course': {'nom': 'Theorbo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'theremin': {'nom': 'Theremin', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'thundersheet': {'nom': 'Thundersheet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'timbales': {'nom': 'Timbales', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'timpani': {'nom': 'Timpani', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'tom-toms': {'nom': 'Toms', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'toy-piano': {'nom': 'Toy Piano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'traverso': {'nom': 'Traverso', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'treble-flute': {'nom': 'Treble Flute', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'treble-kalimba': {'nom': 'Treble Kalimba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'treble-viol': {'nom': 'Treble Viol', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'triangle': {'nom': 'Triangle', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'trombone': {'nom': 'Trombone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'trombone-treble': {'nom': 'Trombone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'trumpet': {'nom': 'trumpet', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tuba': {'nom': 'Tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'tubaphone': {'nom': 'Tubaphone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tubo': {'nom': 'Tubo', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tubular-bells': {'nom': 'Chimes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'tuned-gongs': {'nom': 'Tuned Gongs', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'tuned-klaxon-horns': {'nom': 'Tuned Klaxon Horns', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ukulele': {'nom': 'Ukulele', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ukulele-4-str-tab': {'nom': 'Ukulele', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'ukulele-low-g': {'nom': 'Ukulele', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'upright-piano': {'nom': 'Upright Piano', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'vibraphone': {'nom': 'Vibraphone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'vibraslap': {'nom': 'Vibraslap', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'vienna-horn': {'nom': 'Vienna Horn', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'viola': {'nom': 'Viola', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'viola-da-gamba': {'nom': 'Bass Viol', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'viola-da-gamba-tablature': {'nom': 'Bass Viol', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'violas': {'nom': 'Violas', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'violin': {'nom': 'Violin', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'violins': {'nom': 'Violins', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'violoncello': {'nom': 'Violoncello', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'violoncellos': {'nom': 'Violoncellos', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'violone': {'nom': 'G Violone', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'virginal': {'nom': 'Virginal', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'voice': {'nom': 'Voice', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'vuvuzela': {'nom': 'Vuvuzela', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'wagner-tuba': {'nom': 'wagner-tuba', 'clef': 'FA', 'tona': 'DO', 'octave': 0},
    'warm-synth': {'nom': 'Warm Synthesizer', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'whip': {'nom': 'Whip', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'winds': {'nom': 'Winds', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'women': {'nom': 'Women', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'wood-blocks': {'nom': 'Wood Blocks', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'wooden-wind-chimes': {'nom': 'Wooden Wind Chimes', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'xaphoon': {'nom': 'Pocket Sax', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'xylomarimba': {'nom': 'Xylomarimba', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
    'xylophone': {'nom': 'Xylophone', 'clef': 'SOL', 'tona': 'DO', 'octave': 0},
}
